name: ⭐

env:
  TZ: Asia/Shanghai
  ANDROID_VERSION: 'android16'
  KERNEL_VERSION: '6.12'
  SUB_VERSION: '23_gki'
  KERNEL_NAME: ''
  CCACHE_KEY: ccache-ecsv4-gki-6.12.23

on:
  workflow_dispatch:
    inputs:
      ksu_type:
        description: 'KernelSU分支(ReSukiSU)'
        required: true
        type: choice
        default: 'resukisu'
        options:
          - 'resukisu'
      susfs_enable:
        description: '是否开启susfs(用于增强隐藏环境挂载功能; 可能轻微增加耗电，上游更新导致不稳定时或不需要可关闭)'
        required: true
        type: boolean
        default: 'true'
      kpm_enable:
        description: '是否开启kpm(使用KpatchNext独立实现kpm(支持任意KSU/面具环境); 不需要可保持默认关闭)'
        required: true
        type: boolean
        default: 'true'
      lz4_enable:
        description: '是否安装 lz4 1.10.0+zstd 1.5.7 补丁'
        required: true
        type: boolean
        default: 'true'
      lz4kd_enable:
        description: '是否安装 LZ4KD 补丁(若已开启lz4+zstd补丁则可不开启)'
        required: true
        type: boolean
        default: 'true'
      bbr_enable:
        description: "是否启用bbr算法(优化上行数据,对手机日用无太大意义甚至可能负优化;false关闭,true仅加入算法,default启用算法并设为默认)"
        required: true
        type: choice
        default: 'true'
        options:
          - 'false'
          - 'true'
          - 'default'
      droidspaces_enable:
        description: '是否启用Droidspaces容器支持(轻量化的完整Linux容器支持;false关闭,standard开启容器+ntsync支持,extend开启更多测试支持项)'
        required: true
        type: choice
        default: 'extend'
        options:
          - 'false'
          - 'standard'
          - 'extend'
      better_net:
        description: '是否开启网络功能拓展配置(用于为ipset及需要iptables等高级网络功能内核支持的程序提供支持)'
        required: true
        type: boolean
        default: 'false'
      adios_enable:
        description: '是否启用ADIOS IO调度器支持(提升IO读写性能)'
        required: true
        type: boolean
        default: 'true'
      rekernel_enable:
        description: '是否启用Re-Kernel支持(与Freezer/NoActive等软件配合, 提升应用冻结能力)'
        required: true
        type: boolean
        default: 'true'
      baseband_guard:
        description: '是否开启内核级基带保护(阻止一切对非用户分区的写入，有效防止格机)'
        required: true
        type: boolean
        default: 'true'
      ccache_update:
        description: '更新ccache缓存(将本次编译生成的ccache缓存覆盖至仓库缓存，在更改编译配置、源码或需要刷新缓存时开启)'
        required: true
        type: boolean
        default: 'false'
      ccache_debug:
        description: '是否上传 Ccache调试日志(用于调试, 无需要不必开启)'
        required: true
        type: boolean
        default: 'false'
      kernel_suffix:
        description: '内核后缀(留空默认,开头别加连字符,勿加空格等影响指令运行的保留字符)'
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ksuver: ${{ steps.ksu_version.outputs.ksuver }}
      ak3name: ${{ steps.create_zip.outputs.ak3name }}
    permissions:
      actions: write
      contents: read
    steps:
      - name: 安装环境依赖+初始化源码仓库及llvm-clang19工具链
        run: |
          rm -rf kernel_workspace
          mkdir kernel_workspace
          cd kernel_workspace
          echo "当前仓库：$GITHUB_REPOSITORY"
          echo "当前分支：$GITHUB_REF_NAME"
          
          sudo apt-mark hold firefox &&
          sudo apt-mark hold libc-bin &&
          sudo apt purge man-db &&
          sudo rm -rf /var/lib/man-db/auto-update &&
          sudo apt update &&
          sudo apt-get install -y --no-install-recommends binutils python-is-python3 libssl-dev libelf-dev libdw-dev &
          
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/lib/ccache-x86-64 -O ccache &&
          sudo cp -f ./ccache /usr/bin/ccache &&
          sudo chmod +x /usr/bin/ccache &&
          rm -f ./ccache &
          
          echo "正在克隆源码仓库..."
          aria2c -s16 -x16 -k1M https://github.com/cctv18/android_gki_kernel_common/archive/refs/heads/android16-6.12-2025-06.zip -o common.zip && 
          unzip -q common.zip && 
          mv "android_gki_kernel_common-android16-6.12-2025-06" common &&
          rm -rf common.zip &
          
          echo "正在克隆llvm-clang19工具链..." &&
          mkdir -p clang19 &&
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang19-r536225/clang-r536225.zip -o clang.zip &&
          unzip -q clang.zip -d clang19 &&
          rm -rf clang.zip &
          
          echo "正在克隆Rust 1.82.0工具链..." &&
          mkdir -p rust &&
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang19-r536225/rust.zip -o rust.zip &&
          unzip -q rust.zip -d rust &&
          rm -rf rust.zip &
          
          echo "正在克隆构建工具..." &&
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang19-r536225/build-tools.zip -o build-tools.zip &&
          unzip -q build-tools.zip &&
          rm -rf build-tools.zip &
          
          wait
          echo "所有源码及llvm-clang19工具链初始化完成！"
          echo "正在去除 dirty 后缀..."
          for f in common/scripts/setlocalversion; do
            sed -i 's/ -dirty//g' "$f"
            sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' "$f"
          done

      - name: 配置ccache目录
        run: |
          echo "CCACHE_DIR=$HOME/.ccache_${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }}" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=3G" >> $GITHUB_ENV
          echo "当前磁盘空间："
          df -h
          echo "当前构建内核版本：${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }}"
          if [[ "${{ github.event.inputs.droidspaces_enable }}" != "false" ]]; then
            CCACHE_REAL_KEY=${{ env.CCACHE_KEY }}-Droidspaces
          else
            CCACHE_REAL_KEY=${{ env.CCACHE_KEY }}-none
          fi
          echo "CCACHE_REAL_KEY=$CCACHE_REAL_KEY" >> $GITHUB_ENV

      - name: 载入当前版本内核的 ccache缓存
        uses: actions/cache@v5
        id: ccache-restore
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ env.CCACHE_REAL_KEY }}-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            ${{ env.CCACHE_REAL_KEY }}-${{ runner.os }}-
            ${{ env.CCACHE_REAL_KEY }}-

      - name: 拉取公共预置 ccache 缓存
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "检查本地缓存状态..."
          if [ -d "${{ env.CCACHE_DIR }}" ] && [ "$(ls -A ${{ env.CCACHE_DIR }} 2>/dev/null)" ]; then
            echo "检测到本地已成功载入 ccache 缓存，跳过公共 ccache 拉取！"
            exit 0
          fi
          
          echo "未命中缓存，尝试拉取最新公共 ccache ..."
          mkdir -p ${{ env.CCACHE_DIR }}
          if [[ "${{ github.event.inputs.droidspaces_enable }}" != "false" ]]; then
            FILE_NAME="ccache-${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }}-Droidspaces.tar.zst"
          else
            FILE_NAME="ccache-${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }}.tar.zst"
          fi
          
          if gh release download -p "$FILE_NAME" -R cctv18/public_ccache; then
            echo "成功下载 $FILE_NAME，正在解压..."
            tar -I zstd -xf "$FILE_NAME" -C ${{ env.CCACHE_DIR }}
            echo "公共 ccache 恢复完成！"
          else
            echo "公共 ccache 中未找到对应的 ccache 文件，将进行全量全新编译..."
          fi

      - name: 清除旧 ccache 缓存
        if: inputs.ccache_update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "正在清除仓库中的旧 ccache 缓存..."
          if gh cache delete ${{ env.CCACHE_REAL_KEY }}-${{ runner.os }}-${{ github.ref_name }} -R ${{ github.repository }}; then
            echo "成功删除旧的 ccache 缓存！"
          else
            echo "旧缓存不存在或已被清理！"
          fi
      
      - name: 初始化并配置ccache
        run: |
          export CCACHE_COMPILERCHECK="none"
          export CCACHE_BASEDIR="${{ github.workspace }}"
          export CCACHE_NOHASHDIR="true"
          export CCACHE_NOHARDLINK="true"
          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
          export CCACHE_MAXSIZE="${{ env.CCACHE_MAXSIZE }}"
          
          mkdir -p "$CCACHE_DIR"
          
          echo "配置ccache缓存大小为: $CCACHE_MAXSIZE"
          ccache -M "$CCACHE_MAXSIZE"
          ccache -o compression=true
          
          echo "ccache初始状态:"
          ccache -s
          
          if [ "${{ steps.ccache-restore.outputs.cache-hit }}" == 'true' ]; then
            echo "ccache缓存命中详情:"
            ccache -sv
          fi

      - name: 添加KernelSU
        id: ksu_version
        run: |
          cd kernel_workspace
          echo "正在配置ReSukiSU..."
          curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/refs/heads/suto-hook/kernel/setup.sh" | bash -s suto-hook
          echo 'CONFIG_KSU_FULL_NAME_FORMAT="🌸"' >> ./common/arch/arm64/configs/gki_defconfig
          cd ./KernelSU
          KSU_VERSION=$(expr $(git rev-list --count suto-hook) + 30700 2>/dev/null || echo 114514)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT

      - name: 应用 KernelSU & SUSFS 补丁
        if: inputs.susfs_enable
        run: |
          cd kernel_workspace
          echo "正在添加susfs补丁..."
          git clone --depth=1 https://github.com/cctv18/susfs4oki.git susfs4ksu -b oki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}
          cp ./susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch ./common/
          cp ./susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp ./susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
          cd ./common
          patch -p1 < 50_add_susfs_in_gki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch || true
          
      - name: 应用lz4 1.10.0 & zstd 1.5.7补丁
        if: inputs.lz4_enable
        run: |
          echo "正在添加lz4 1.10.0 & zstd 1.5.7补丁…"
          cd kernel_workspace
          git clone --depth=1 https://github.com/$GITHUB_REPOSITORY.git -b $GITHUB_REF_NAME $GITHUB_ACTOR
          cp ./$GITHUB_ACTOR/zram_patch/001-lz4.patch ./common/
          cp ./$GITHUB_ACTOR/zram_patch/002-zstd.patch ./common/
          cd ./common
          patch -p1 < 001-lz4.patch || true
          patch -p1 < 002-zstd.patch || true

      - name: 应用 lz4kd 补丁
        if: inputs.lz4kd_enable
        run: |
          echo "正在添加lz4kd补丁…"
          cd kernel_workspace/common
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/other_patch/lz4kd.patch
          patch -p1 -F 3 < lz4kd.patch || true
          
      - name: 添加SUSFS 配置项
        if: inputs.susfs_enable
        run: |
          cd kernel_workspace
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MAP=y" >> ./common/arch/arm64/configs/gki_defconfig
          
      - name: 添加 KSU & 其他配置项
        run: |
          cd kernel_workspace
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          if [[ "${{ github.event.inputs.susfs_enable }}" == "false" ]]; then
            echo "CONFIG_KSU_SUSFS=n" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./common/arch/arm64/configs/gki_defconfig
          if [[ "${{ github.event.inputs.lz4kd_enable }}" == "true" ]]; then
            echo "CONFIG_ZSMALLOC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_CRYPTO_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_CRYPTO_LZ4K=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_CRYPTO_842=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_ZRAM_BACKEND_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_ZRAM_BACKEND_LZ4K=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_ZRAM_BACKEND_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_ZRAM_BACKEND_842=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y" >> ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          echo "CONFIG_HEADERS_INSTALL=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_RUST=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_ANDROID_BINDER_IPC_RUST=m" >> ./common/arch/arm64/configs/gki_defconfig
          cd common
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/other_patch/cve-2026-43499-rtmutex-6.12.patch
          patch -p1 -F 3 < cve-2026-43499-rtmutex-6.12.patch
          
      - name: 启用网络功能增强优化配置
        if: inputs.better_net
        run: |
          cd kernel_workspace
          echo "CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_NETFILTER_XT_SET=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_MAX=65534" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_BITMAP_IP=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_BITMAP_IPMAC=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_BITMAP_PORT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_IP=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_IPMARK=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_IPPORT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_IPPORTIP=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_IPPORTNET=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_IPMAC=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_MAC=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_NETPORTNET=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_NET=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_NETNET=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_NETPORT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_HASH_NETIFACE=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_SET_LIST_SET=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_NAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_TARGET_MASQUERADE=y" >> ./common/arch/arm64/configs/gki_defconfig
          cd common
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/other_patch/config.patch
          patch -p1 -F 3 < config.patch || true

      - name: 添加 BBR 等一系列拥塞控制算法
        run: |
          if [[ "${{ github.event.inputs.bbr_enable }}" != "false" ]]; then
            echo "正在添加BBR等拥塞控制算法..."
            cd kernel_workspace
            echo "CONFIG_TCP_CONG_ADVANCED=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_CUBIC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_VEGAS=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_NV=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_WESTWOOD=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_HTCP=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_BRUTAL=y" >> ./common/arch/arm64/configs/gki_defconfig
            if [[ "${{ github.event.inputs.bbr_enable }}" == "default" ]]; then
              echo "正在将BBR设为默认拥塞控制算法..."
              echo "CONFIG_DEFAULT_TCP_CONG=bbr" >> ./common/arch/arm64/configs/gki_defconfig
            else
              echo "CONFIG_DEFAULT_TCP_CONG=cubic" >> ./common/arch/arm64/configs/gki_defconfig
            fi
          fi

      - name: 启用 Droidspaces 容器支持
        run: |
          if [[ "${{ github.event.inputs.droidspaces_enable }}" != "false" ]]; then
            echo "正在启用 Droidspaces 容器支持..."
            cd kernel_workspace/common
            wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/droidspaces_patch/fix_sysvipc_kabi_a16-6.12.patch
            patch -p1 -F 3 < fix_sysvipc_kabi_a16-6.12.patch || true
            wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/droidspaces_patch/fix_oplus_bsp_midas.patch
            patch -p1 -F 3 < fix_oplus_bsp_midas.patch || true
            wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/droidspaces_patch/ddl_hit_hook.patch
            patch -p1 -F 3 < ddl_hit_hook.patch || true
            wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/droidspaces_patch/ntsync_compat_${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch
            patch -p1 -F 3 < ntsync_compat_${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch || true
            echo "CONFIG_PID_NS=y" >> ./arch/arm64/configs/gki_defconfig
            echo "CONFIG_IPC_NS=y" >> ./arch/arm64/configs/gki_defconfig
            echo "CONFIG_USER_NS=y" >> ./arch/arm64/configs/gki_defconfig
            echo "CONFIG_SYSVIPC=y" >> ./arch/arm64/configs/gki_defconfig
            echo "CONFIG_DEVTMPFS=y" >> ./arch/arm64/configs/gki_defconfig
            echo "CONFIG_NAMESPACES=y" >> ./arch/arm64/configs/gki_defconfig
            echo "CONFIG_POSIX_MQUEUE=y" >> ./arch/arm64/configs/gki_defconfig
            echo "CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y" >> ./arch/arm64/configs/gki_defconfig
            echo "CONFIG_NETFILTER_XT_TARGET_LOG=y" >> ./arch/arm64/configs/gki_defconfig
            echo "CONFIG_NETFILTER_XT_MATCH_RECENT=y" >> ./arch/arm64/configs/gki_defconfig
            echo "CONFIG_NTSYNC=y" >> ./arch/arm64/configs/gki_defconfig
            if [[ "${{ github.event.inputs.droidspaces_enable }}" == "extend" ]]; then
              echo "正在启用容器环境扩展支持..."
              echo "CONFIG_BT_HCIVHCI=y" >> ./arch/arm64/configs/gki_defconfig
              echo "CONFIG_STATIC_USERMODEHELPER=n" >> ./arch/arm64/configs/gki_defconfig
            fi
          fi

      - name: 启用ADIOS IO调度器
        if: inputs.adios_enable
        run: |
          echo "正在启用ADIOS IO调度器..."
          cd kernel_workspace
          echo "CONFIG_MQ_IOSCHED_ADIOS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_MQ_IOSCHED_DEFAULT_ADIOS=y" >> ./common/arch/arm64/configs/gki_defconfig

      - name: 启用Re-Kernel支持
        if: inputs.rekernel_enable
        run: |
          echo "正在启用Re-Kernel支持..."
          cd kernel_workspace
          echo "CONFIG_REKERNEL=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_REKERNEL_NETWORK=y" >> ./common/arch/arm64/configs/gki_defconfig

      - name: 启用内核级基带保护
        if: inputs.baseband_guard
        run: |
          echo "正在启用内核级基带保护支持..."
          cd kernel_workspace
          echo "CONFIG_BBG=y" >> ./common/arch/arm64/configs/gki_defconfig
          cd ./common
          curl -sSL https://github.com/cctv18/Baseband-guard/raw/master/setup.sh | bash
          sed -i '/^config LSM$/,/^help$/{ /^[[:space:]]*default/ { /baseband_guard/! s/selinux/selinux,baseband_guard/ } }' security/Kconfig

      - name: 添加制作名称
        run: |
          cd kernel_workspace
          echo "替换内核版本后缀..."
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            echo "当前内核版本后缀：${{ github.event.inputs.kernel_suffix }}"
            for f in ./common/scripts/setlocalversion; do
              sed -i "\$s|echo \"\\\$res\"|echo \"-${{ github.event.inputs.kernel_suffix }}\"|" "$f"
            done
            sudo sed -i 's/-4k/-${{ github.event.inputs.KERNEL_SUFFIX }}/g' ./common/arch/arm64/configs/gki_defconfig
          else
            echo "当前内核版本后缀：${{ env.KERNEL_NAME }}"
            for f in ./common/scripts/setlocalversion; do
              sed -i "\$s|echo \"\\\$res\"|echo \"-${{ env.KERNEL_NAME }}\"|" "$f"
            done
            sudo sed -i 's/-4k/-${{ env.KERNEL_NAME }}/g' ./common/arch/arm64/configs/gki_defconfig
          fi
          sed -i 's/${scm_version}//' ./common/scripts/setlocalversion
          echo "CONFIG_LOCALVERSION_AUTO=n" >> ./common/arch/arm64/configs/gki_defconfig
           
      - name: 构建内核
        run: |
          WORKDIR="$(pwd)"
          export PATH="/usr/lib/ccache:$PATH"
          export PATH="$WORKDIR/kernel_workspace/clang19/bin:$PATH"
          export PATH="$WORKDIR/kernel_workspace/build-tools/bin:$PATH"
          export PATH="$WORKDIR/kernel_workspace/rust/bin:$PATH"
          export CLANG_DIR="$WORKDIR/kernel_workspace/clang19/bin"
          CLANG_VERSION="$($CLANG_DIR/clang --version | head -n 1)"
          LLD_VERSION="$($CLANG_DIR/ld.lld --version | head -n 1)"
          RUSTC_VERSION="$(rustc -V 2>/dev/null | head -n1)"
          BINDGEN_VERSION="$(bindgen --version 2>/dev/null | head -n1)"
          echo "编译器信息:"
          echo "Clang版本: $CLANG_VERSION"
          echo "LLD版本: $LLD_VERSION"
          echo "Rustc版本: $RUSTC_VERSION"
          echo "Bindgen版本: $BINDGEN_VERSION"
          pahole_version=$(pahole --version 2>/dev/null | head -n1); [ -z "$pahole_version" ] && echo "pahole版本：未安装" || echo "pahole版本：$pahole_version"
          
          export CCACHE_LOGFILE="${{ github.workspace }}/kernel_workspace/ccache.log"
          export CCACHE_COMPILERCHECK="none"
          export CCACHE_BASEDIR="${{ github.workspace }}"
          export CCACHE_NOHASHDIR="true"
          export CCACHE_NOHARDLINK="true"
          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
          export CCACHE_MAXSIZE="3G"
          export CCACHE_IS_KERNEL_COMPILING="true"
          echo "sloppiness = file_stat_matches,include_file_ctime,include_file_mtime,pch_defines,file_macro,time_macros" >> "$CCACHE_DIR/ccache.conf"
          
          cd kernel_workspace/common
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/lib/libfakestat.so
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/lib/libfaketimeMT.so
          chmod 777 ./*.so
          export FAKESTAT="2025-05-25 12:00:00"
          export FAKETIME="@2025-05-25 13:00:00"
          echo "FAKESTAT=$FAKESTAT" >> $GITHUB_ENV
          echo "FAKETIME=$FAKETIME" >> $GITHUB_ENV
          SO_DIR=$(pwd)
          export PRELOAD_LIBS="$SO_DIR/libfakestat.so $SO_DIR/libfaketimeMT.so"
          export REAL_CLANG_PATH="$WORKDIR/kernel_workspace/clang19/bin/clang"
          echo '#!/bin/bash' > cc-wrapper
          echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> cc-wrapper
          echo 'export FAKESTAT="'$FAKESTAT'"' >> cc-wrapper
          echo 'export FAKETIME="'$FAKETIME'"' >> cc-wrapper
          echo 'ccache $REAL_CLANG_PATH "$@"' >> cc-wrapper
          echo '#!/bin/bash' > ld-wrapper
          echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> ld-wrapper
          echo 'export FAKESTAT="'$FAKESTAT'"' >> ld-wrapper
          echo 'export FAKETIME="'$FAKETIME'"' >> ld-wrapper
          echo 'ld.lld "$@"' >> ld-wrapper
          
          echo '#!/bin/bash' > test-wrapper.sh
          echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> test-wrapper.sh
          echo 'export FAKESTAT="'$FAKESTAT'"' >> test-wrapper.sh
          echo 'export FAKETIME="'$FAKETIME'"' >> test-wrapper.sh
          echo 'echo ">>> Wrapper 内部环境检查完毕."' >> test-wrapper.sh
          echo 'exec "$@"' >> test-wrapper.sh
          chmod +x test-wrapper.sh
          echo "--- [Wrapper Test] 正在测试 (date) 命令 ---"
          ./test-wrapper.sh date
          echo "--- [Wrapper Test] 正在测试 (stat) 命令 ---"
          ./test-wrapper.sh stat ./Makefile
          echo "--- [Wrapper
